import React,{useState} from 'react';
import type {PostItem} from '../types';
import {apiFetch} from '../lib/supabase';
interface Props {posts:PostItem[];onOpenPostInQueue?:(id:string)=>void;onPostUpdated:(post:PostItem)=>void;}
export function CollaborationRoom({posts,onOpenPostInQueue,onPostUpdated}:Props) {
 const shared=posts.filter(p=>!p.source);
 const [selected,setSelected]=useState(shared[0]?.id||''),[text,setText]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const post=shared.find(p=>p.id===selected);
 return <section className="bg-white rounded-3xl p-6 border border-slate-200 space-y-5"><h1 className="text-xl font-bold">Staff collaboration</h1><p className="text-sm text-slate-600">Comments are saved with the shared post and refreshed every 30 seconds.</p><label className="block text-sm">Post<select value={selected} onChange={e=>{setSelected(e.target.value);setText('');setError('');}} className="block border rounded-lg p-2 mt-2 w-full"><option value="">Select a shared post</option>{shared.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label>
 {post && <><button onClick={()=>onOpenPostInQueue?.(post.id)} className="text-purple-700 text-sm">Open post in queue</button><div className="space-y-4 max-h-96 overflow-auto">{post.comments.length?post.comments.map(c=><article key={c.id} className="bg-slate-50 rounded-xl p-4"><p className="text-sm font-semibold">{c.author} <span className="text-xs text-slate-500">{new Date(c.createdAt).toLocaleString()}</span></p><p className="whitespace-pre-wrap text-sm mt-2">{c.content}</p></article>):<p className="text-sm text-slate-500">No comments yet.</p>}</div><form className="space-y-3" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const response=await apiFetch(`/api/posts/${post.id}/comments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:text,expectedRevision:post.revision})});const data=await response.json();if(!response.ok)throw new Error(data.error);onPostUpdated(data.post);setText('');}catch(error){setError((error as Error).message);}finally{setBusy(false);}}}><label className="text-sm block">Comment<textarea value={text} onChange={e=>setText(e.target.value)} required maxLength={3000} className="block w-full border rounded-lg p-3 mt-2" /></label>{error && <p role="alert" className="text-rose-700 text-sm">{error} Your comment is still here.</p>}<button disabled={busy||!text.trim()} className="px-4 py-2 bg-purple-600 text-white rounded-full disabled:opacity-50">{busy?'Saving…':'Save comment'}</button></form></>}
 {!shared.length && <p className="text-sm text-slate-600">Save a draft or submit a post to start a conversation.</p>}
 </section>;
}
